"""Presentation formatting — IL ports outside Game.Logic (NumberFormat, StatsFormat, …)."""

from .format_currency import format_currency
from .format_item import format_secondary_stats, format_secondary_stats_collection
from .format_mount import get_mount_display_name, get_mount_name
from .format_pet import (
	format_pet_stats,
	format_pet_stats_upgrade_mode,
	get_pet_display_name,
	get_pet_name,
)
from .format_skill import (
	format_skill_description,
	format_skill_description_args,
	get_skill_description_template,
	get_skill_display_name,
	get_skill_name,
)
from .format_techtree import (
	TechTreeNodeDescriptionLine,
	build_tech_tree_node_description,
	build_tech_tree_node_description_lines,
	build_tech_tree_node_title,
	format_tech_tree_active_research_suffix,
	format_tech_tree_category_progress,
	format_tech_tree_complete_suffix,
	get_tech_tree_node_title,
	parenthesized_text,
	tier_roman_numeral,
)
from .format_time import format_hatch_duration, format_timer_duration
from .localizer import (
	format_bracketed_entity_title,
	get_ascension_name,
	get_currency_name,
	get_dungeon_drop_text,
	get_dungeon_name,
	get_rarity_name,
)
from .localizer_base import (
	clear_localization_cache,
	format_localized,
	get_localized,
	get_translation,
	is_english,
	load_available_languages,
	localizations_dir,
	localize,
	loc_id_for_key,
	resolve_language,
	selected_language,
	set_selected_language,
)
from .mapping_loc import (
	ascension_name,
	loc_id_from_entry,
	localized_desc_from_entry,
	localized_name_from_entry,
	rarity_name,
)
from .number_format import (
	format_currency_value,
	format_damage,
	format_drop_chance_percentage,
	format_level,
	format_level_plus_one,
	format_multiplier,
	format_percentage,
	format_power,
	format_progress_pair,
	format_stat,
	max_progress_label,
	maxed_progress_label,
)
from .numbers import (
	SUFFIXES,
	RoundingMode,
	format as format_number,
	format_digits,
	format_long,
	format_multiplier_1_significant_digits,
	format_multiplier_3_significant_digits,
	format_multiplier_fixed,
	format_with_format_string,
	round_digits,
	round_down,
	round_up,
	truncate_to_two_decimals,
)
from .stats_format import (
	format_stat_comparison_flat,
	format_stat_delta_display,
	format_stat_display,
	format_stat_string,
	get_stat_name,
)
from .stats_localizer import (
	get_attack_type_name,
	get_dungeon_text,
	get_stat_type_name,
	translate_stat_target,
)

__all__ = [
	"SUFFIXES",
	"RoundingMode",
	"TechTreeNodeDescriptionLine",
	"ascension_name",
	"build_tech_tree_node_description",
	"build_tech_tree_node_description_lines",
	"build_tech_tree_node_title",
	"clear_localization_cache",
	"format_bracketed_entity_title",
	"format_currency",
	"format_currency_value",
	"format_damage",
	"format_digits",
	"format_drop_chance_percentage",
	"format_hatch_duration",
	"format_level",
	"format_level_plus_one",
	"format_localized",
	"format_long",
	"format_multiplier",
	"format_multiplier_1_significant_digits",
	"format_multiplier_3_significant_digits",
	"format_multiplier_fixed",
	"format_number",
	"format_percentage",
	"format_pet_stats",
	"format_pet_stats_upgrade_mode",
	"format_power",
	"format_progress_pair",
	"format_tech_tree_active_research_suffix",
	"format_tech_tree_category_progress",
	"format_tech_tree_complete_suffix",
	"format_secondary_stats",
	"format_secondary_stats_collection",
	"format_skill_description",
	"format_skill_description_args",
	"format_stat",
	"format_stat_comparison_flat",
	"format_stat_delta_display",
	"format_stat_display",
	"format_stat_string",
	"format_timer_duration",
	"format_with_format_string",
	"get_ascension_name",
	"get_attack_type_name",
	"get_currency_name",
	"get_dungeon_drop_text",
	"get_dungeon_name",
	"get_dungeon_text",
	"get_localized",
	"get_mount_display_name",
	"get_mount_name",
	"get_pet_display_name",
	"get_pet_name",
	"get_rarity_name",
	"get_skill_description_template",
	"get_skill_display_name",
	"get_skill_name",
	"get_stat_name",
	"get_stat_type_name",
	"get_tech_tree_node_title",
	"get_translation",
	"is_english",
	"load_available_languages",
	"localizations_dir",
	"localize",
	"loc_id_for_key",
	"loc_id_from_entry",
	"localized_desc_from_entry",
	"localized_name_from_entry",
	"max_progress_label",
	"maxed_progress_label",
	"parenthesized_text",
	"rarity_name",
	"resolve_language",
	"round_digits",
	"round_down",
	"round_up",
	"selected_language",
	"set_selected_language",
	"tier_roman_numeral",
	"translate_stat_target",
	"truncate_to_two_decimals",
]
