from __future__ import annotations

"""Metaplay fixed-point math (IL: Metaplay.Core.Math.F64 / FD6 / Int128)."""

from core.metaplaymath.config_values import (
	config_f64_raw,
	config_fd6_raw,
	normalize_ascension_config,
	normalize_equipment_info,
	normalize_level_stats_entries,
	normalize_mount_upgrade_config,
	normalize_pet_upgrade_config,
	normalize_secondary_stat_row,
	normalize_sets_tier,
	normalize_skill_config,
	normalize_skill_passive_config,
	normalize_stat_config_row,
	normalize_stat_contribution_row,
	normalize_stat_contribution_rows,
	secondary_stat_lower_f64_raw,
	secondary_stat_upper_f64_raw,
	skill_level_fd6_raw,
	stat_config_default_fd6_raw,
	stat_contribution_value_fd6_raw,
)
from core.metaplaymath.f64 import (
	F64,
	F64_ONE_RAW,
	F64_SCALE,
	F64Like,
	f64_add_raw,
	f64_clamp01,
	f64_clamp01_raw,
	f64_div_raw,
	f64_from_raw,
	f64_greater_than_or_equal_raw,
	f64_less_than_raw,
	f64_lerp,
	f64_lerp_raw,
	f64_lerp_raw_from_floats,
	f64_lerp_raw_from_t_raw,
	f64_mul_raw,
	f64_next_f64_in_range_raw,
	f64_ratio,
	f64_ratio10,
	f64_ratio100,
	f64_ratio1000,
	f64_sub_raw,
	f64_to_raw,
)
from core.metaplaymath.fd6 import (
	FD6,
	FD6_PRECISION,
	FD6Like,
	fd6_add_raw,
	fd6_div_raw,
	fd6_from_double,
	fd6_from_f64,
	fd6_from_f64_raw,
	fd6_from_int,
	fd6_from_long,
	fd6_get_double,
	fd6_greater_than_or_equal_raw,
	fd6_less_than_raw,
	fd6_mul_f64_raw,
	fd6_mul_raw,
	fd6_sub_raw,
	fd6_to_double,
	fd6_truncate,
	format_fd6_raw,
)
from core.metaplaymath.int128 import add as int128_add
from core.metaplaymath.int128 import div as int128_div
from core.metaplaymath.int128 import from_i64 as int128_from_i64
from core.metaplaymath.int128 import i64 as int128_i64
from core.metaplaymath.int128 import less_than as int128_less_than
from core.metaplaymath.int128 import mul as int128_mul
from core.metaplaymath.int128 import sign_extend_128
from core.metaplaymath.int128 import sub as int128_sub
from core.metaplaymath.int128 import to_double as int128_to_double
from core.metaplaymath.types import F64Raw, FD6Raw

__all__ = [
	"config_f64_raw",
	"config_fd6_raw",
	"normalize_ascension_config",
	"normalize_equipment_info",
	"normalize_level_stats_entries",
	"normalize_mount_upgrade_config",
	"normalize_pet_upgrade_config",
	"normalize_secondary_stat_row",
	"normalize_sets_tier",
	"normalize_skill_config",
	"normalize_skill_passive_config",
	"normalize_stat_config_row",
	"normalize_stat_contribution_row",
	"normalize_stat_contribution_rows",
	"secondary_stat_lower_f64_raw",
	"secondary_stat_upper_f64_raw",
	"skill_level_fd6_raw",
	"stat_config_default_fd6_raw",
	"stat_contribution_value_fd6_raw",
	"F64",
	"F64_ONE_RAW",
	"F64Raw",
	"F64_SCALE",
	"F64Like",
	"FD6",
	"FD6_PRECISION",
	"FD6Like",
	"FD6Raw",
	"f64_add_raw",
	"f64_clamp01",
	"f64_clamp01_raw",
	"f64_div_raw",
	"f64_from_raw",
	"f64_greater_than_or_equal_raw",
	"f64_less_than_raw",
	"f64_lerp",
	"f64_lerp_raw",
	"f64_lerp_raw_from_floats",
	"f64_lerp_raw_from_t_raw",
	"f64_mul_raw",
	"f64_next_f64_in_range_raw",
	"f64_ratio",
	"f64_ratio10",
	"f64_ratio100",
	"f64_ratio1000",
	"f64_sub_raw",
	"f64_to_raw",
	"fd6_add_raw",
	"fd6_div_raw",
	"fd6_from_double",
	"fd6_from_f64",
	"fd6_from_f64_raw",
	"fd6_from_int",
	"fd6_from_long",
	"fd6_get_double",
	"fd6_greater_than_or_equal_raw",
	"fd6_less_than_raw",
	"fd6_mul_f64_raw",
	"fd6_mul_raw",
	"fd6_sub_raw",
	"fd6_to_double",
	"fd6_truncate",
	"format_fd6_raw",
	"int128_add",
	"int128_div",
	"int128_from_i64",
	"int128_i64",
	"int128_less_than",
	"int128_mul",
	"int128_sub",
	"int128_to_double",
	"sign_extend_128",
]
